<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
      <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
      <UseWPF>true</UseWPF>
      <Description>OxyPlot is a plotting library for .NET. This package targets WPF applications and uses the SkiaSharp renderer.</Description>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <GenerateDocumentationFile>True</GenerateDocumentationFile>
      <PackageTags>plotting plot charting chart wpf</PackageTags>
      <LangVersion>8</LangVersion>
      <SignAssembly>true</SignAssembly>
      <AssemblyOriginatorKeyFile>OxyPlot.SkiaSharp.Wpf.snk</AssemblyOriginatorKeyFile>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="4.151.1" />
    <None Include="OxyPlot.SkiaSharp.Wpf.snk" />
    <None Include="VisualStudioToolsManifest.xml" Pack="true" PackagePath="tools" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot.SkiaSharp\OxyPlot.SkiaSharp.csproj" />
    <ProjectReference Include="..\OxyPlot.Wpf.Shared\OxyPlot.Wpf.Shared.csproj" />
    <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>

