<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
        <UseWPF>true</UseWPF>
        <LangVersion>8</LangVersion>
        <Nullable>enable</Nullable>
        <PackageId>OxyPlot.Core</PackageId>
        <Description>OxyPlot is a plotting library for .NET. This is the core library including the foundation classes and plot model. To display the plots, you also need to add a platform-specific OxyPlot package that contains a PlotView component.</Description>
        <PackageTags>plotting plot charting chart</PackageTags>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>OxyPlot.snk</AssemblyOriginatorKeyFile>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <LangVersion>9</LangVersion>
        <NoWarn>$(NoWarn);CS0618</NoWarn>
        <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
        <EnableNETAnalyzers>False</EnableNETAnalyzers>
    </PropertyGroup>
    <ItemGroup>
        <None Include="OxyPlot.snk" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
    </ItemGroup>
</Project>
