<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFramework>net8.0-windows8.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>8</LangVersion>
    <Description>OxyPlot is a plotting library for .NET. This package is the base for WPF PlotView implementations.</Description>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageTags>plotting plot charting chart wpf</PackageTags>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>OxyPlot.Wpf.Shared.snk</AssemblyOriginatorKeyFile>
    <NuGetAudit>False</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <None Include="OxyPlot.Wpf.Shared.snk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
  </ItemGroup>
</Project>
