<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>8</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Copyright>Copyright (c) 2020 OxyPlot contributors</Copyright>
      <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Authors>OxyPlot contributors</Authors>
    <Description>OxyPlot is a plotting library for .NET. This package provides rendering based on SkiaSharp.</Description>
    <PackageTags>plotting plot charting chart skiasharp skia pdf</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>OxyPlot.SkiaSharp.snk</AssemblyOriginatorKeyFile>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.119.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="OxyPlot.SkiaSharp.snk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="1.2.25" />
  </ItemGroup>
</Project>
